---
title: "Ames Housing Project"
author: "Quyen Duong, Amin Jamali, Camille Nigon, Pascal Waser"
date: "12/22/2021"
output: html_document
---

```{r setup, include=FALSE}
# Set the default mode for all the chunks
knitr::opts_chunk$set(message = FALSE, warning = FALSE, fig.align = "center", 
                      fig.height = 5, fig.width = 8)
```

```{r load-packages, include = FALSE}
# Load packages
library(dplyr)
library(ggplot2)
library(tidyverse)
library(scales)                      # formatting numbers on axis ggplot
library(gridExtra)
library(tidyr)
library(readr)
library(knitr)
library(lubridate)                   # to format date
library(egg)                         # plot layout 
library(PerformanceAnalytics)        # correlation matrix
library(GGally)                      # correlation matrix
library(corrplot)                    # correlation matrix
library(Hmisc)                       # correlation matrix
library(psych)                       # summary statistics
library(caret)                       # split data train-test
library(broom)                       # visualize fitted linear with categorical variable
library(MASS)
library(conflicted)                  # set conflict
library(ggthemes)
library(grid)
library(leaps)                       # stepwise selection
library(caret)                       # splitting train-test, SVM

# Set conflict preference
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
```

```{r load-data, include = FALSE}
# Load data
d_house <- read.csv("dataset/AmesHousing.csv", stringsAsFactors = TRUE) %>% 
  as_tibble()

# Check the variables
glimpse(d_house)

# Exclude the irrelevant variables
d_house <- d_house %>% 
  select(-c(Order, PID))

# Exclude the columns with 49% missing value
d_house <- d_house %>% 
  select(-c(Alley, Fireplace.Qu, Pool.QC, Fence, Misc.Feature))

# Remove the 1 NA rows from two important columns
d_house <- d_house %>% drop_na(Garage.Cars, Total.Bsmt.SF)
```

# Train and test data

```{r train-test}
set.seed(12)
# We choose 70% for train data
indices <- createDataPartition(d_house$SalePrice, p = 0.70, list = F)

# Train data
d_train <- d_house %>%
  slice(indices)

# Test data
d_test <- d_house %>%
  slice(-indices) 
```



